### PR TITLE
4255 - Add VueJS example with Tag Component

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Implemented the ids web components with vuejs framework.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/4255

**Steps necessary to review your pull request (required)**:
- Pull this branch
- Go to vuejs project folder `enterprise-wc-examples/vue-ids-wc`
- Run `npm install`
- Then `npm run serve`
- Go to http://localhost:8080/

### CODE REVIEW

**Review by jmacaluso711 — CHANGES_REQUESTED** [review]
Looking good... Maybe add an example of the clickable and dismissible tag, so we can test out the events?

**Comment by tmcconechy** [comment]
Yes looks good. It works pretty seamlessly. Can you add maybe some more notes to the README.MD on anything one needs to consider to get the web components working.

Also check out the new angular-ids-wc -> maybe we can format this one the same way so its showing the same things as that test page. 

vue-ids-wc
angular-ids-wc	
react-ids-wc

**Comment by ericangeles** [comment]
@tmcconechy @jmacaluso711 you can take a look again

**Review by tmcconechy — APPROVED** [review]
Looks good !

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
