### PR TITLE
Add component types and fix typo in IdsCalendar example

### PR DESCRIPTION
**Pull request by jmacaluso711**
Adds missing component imports and fixes a type on the eventsData method

Fixes https://github.com/infor-design/enterprise-wc/issues/966

### CODE REVIEW

**Comment by jmacaluso711** [comment]
@jdilag90 @tmcconechy there was a typo in the component example that was preventing the events from showing. Adding the component imports actually pointed that out, otherwise it would have been hard to catch 👍

**Comment by jdilag90** [comment]
@jmacaluso711 Nice! Caught that as well, but wondering why the details and legend pane aren't showing in the angular example. 

For testing purposes, adding this inside `ngAfterViewInit` seems to toggle the panes correctly.
```
    this.calendar.nativeElement.showLegend = true;
    this.calendar.nativeElement.showDetails = true;
```

Any ideas?

**Comment by tmcconechy** [comment]
Can we maybe edit the events from being in 2018/2019 to 2022?

**Comment by jdilag90** [comment]
> Can we maybe edit the events from being in 2018/2019 to 2022?

I think I have an old script that can shift the event dates by 3 or 4 years.
Do you want this updated in both the angular and enterprise-wc repos?

**Comment by tmcconechy** [comment]
Sure, i think it makes more sense so you dont have to go back several years to see the data and it doesnt "date us back"

**Comment by jmacaluso711** [comment]
> @jmacaluso711 Nice! Caught that as well, but wondering why the details and legend pane aren't showing in the angular example.
> 
> For testing purposes, adding this inside `ngAfterViewInit` seems to toggle the panes correctly.
> 
> ```
>     this.calendar.nativeElement.showLegend = true;
>     this.calendar.nativeElement.showDetails = true;
> ```
> 
> Any ideas?

I noticed that also.. looks the like the legend appears on smaller screens... Just tested, the details show if you use property binding in the template `[attr.show-details]="true"`

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
