### PR TITLE
638 React Examples Build Errors fixes

### PR DESCRIPTION
**Pull request by andriivarhanov**
React Examples: Fix some terminal/console errors. Fixed IdsText layout. Fixed e2e tests

- pull
- go to `cd react-ids-wc`
- `rm -rf node_modules package-lock.json`
- `npm install`
- `npm start`

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
thanks @andriivarhanov 

Just an FYI i had errors on ids-renderloop and figured we really didnt need to show it so i removed it but if its working now looks good.

I had to do the steps you mentioned including removing the package lock or i got some es module errors. Also had to be on node 16. So updated the steps in the readme.

The only issue i see now is some pages have errors like http://localhost:3000/ids-breadcrumb
```
VM79:1 Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at HTMLDocument.createElement (<anonymous>:1:1536)
```

Any idea about that? Is it because i removed the @webcomponents polyfill (i thought it was for IE 9)

**Comment by andriivarhanov** [comment]
@tmcconechy it looks like the error is not related to webcomponents polyfill, still got the error with the polyfill. Checking now if I can fix it

**Comment by andriivarhanov** [comment]
@tmcconechy I've added some adjustments https://github.com/infor-design/enterprise-wc-examples/pull/9/commits/f1b3ec6a5c8d55a61b8de28d3059ed1f2466323e to make it work, there is some issue where some web components like input, checkbox and more can't initialize if wc js added before react jsx. What is below throws the error:

```html
<html>
  <head>
    <script src="react-bundle-with-wc-library.js"></script>
  </head>
  <body>
    <ids-tag clickable="true" id="ids-clickable-tag">Added in Markup</ids-tag>
  </body>
</html>
```
it works
```html
<html>
  <head>
    <script src="react-bundle-main.js"></script>
    <script src="enterprise-wc-chunk.js"></script>
  </head>
  <body>
    <ids-tag clickable="true" id="ids-clickable-tag">Added in Markup</ids-tag>
  </body>
</html>
```

no errors on pages now except for data grid, something with formatters, need more time to fix

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
Great - works good for now. Thanks a lot @andriivarhanov - anything else you want to fix we can do a later PR

**Pull request merged**
