### PR TITLE
4631 - Update and check TypeScript angular samples

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates and check how we implement the IDS Web Components with TypeScript in Angular.

**Related github/jira issue (required)**:

Parial fix https://github.com/infor-design/enterprise/issues/4631

These includes,
- Routing for the components (Open for discussions)
- Added two components with strict type when declaring properties (Tag and Label)

Will Add
- Testing
- Usage of supported Methods/Events/Settings (When add more web components)

Will also implement to non-Angular frameworks (React & Vue)

**Steps necessary to review your pull request (required)**:
- Pull this branch
- Go to project folder `cd enterprise-wc-examples/angular-ids-wc`
- Run `npm i`
- Then `ng serve`
- Go to http://localhost:4200/components
- Test and check the codes on how the routings, folder structure, and making properties strict type

### CODE REVIEW

**Comment by ericangeles** [comment]
Remaining ToDo items:
- Testing
- Update and use TypeScript in React and Vue
- Supported methods/Events/Settings (If some components will be available?)

@tmcconechy

**Comment by tmcconechy** [comment]
@ericangeles I think this is OK for now - but i wouldnt spend a lot of time on the way the app and routing works while we figure out the plan for that. What im thinking is a link per page on the main page to a single example but not sure yet.

We also want to make that the same for all (4) projects. So i wouldn't worry about it.

Is any way to do the routing with less files?

For testing - we also need to figure that out so wouldnt spend much time on that either right now. 

Also dont need to make the React and Vue use typescript. I think i would ONLY do that if that is the most used and most recommended way to use those frameworks.

So overall nothing wrong with this just need to make some more decisions on that part and perhaps just focus that typescript works for now.

**Comment by ericangeles** [comment]
Thanks for the feedback @tmcconechy. So this will be merge to the master or are we gonna close this now?

**Comment by tmcconechy** [comment]
I guess we can just close? Unless there is anything related to Typescript specifically we want to keep?

**Comment by ericangeles** [comment]
@tmcconechy sure, we can close this then.

**Pull request closed without merging**
